[workspace]
members = ["cli"]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "s"

[package]
name = "tack"
version = "0.1.5"
description = "A desktop task manager for humans and AI agents"
authors = ["Pimatis"]
edition = "2021"
default-run = "tack-app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tack_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "tack-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-process = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-window-state = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
dirs = "5"
chrono = { version = "0.4", features = ["serde"] }
notify = "6"
base64 = "0.22"
tiny_http = "0.12"
tauri-plugin-updater = "2.10.1"
